name: Push Images to registry
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  RegistryPush:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
    - name: Determine if its a push or pull request
      id: tag
      run: |
        if [ ${{ github.event_name }} == 'pull_request' ]; then
          # Pull requests are tagged with the name of their branch.
          echo "::set-output name=tag::${{ github.head_ref }}";
        else
          ref=${{ github.ref }}
          if [ "${ref}" == 'refs/heads/master' ]; then
            # Commits to master are tagged as latest.
            echo "::set-output name=tag::latest"
          else
            # Because we only trigger push builds for master and version tags,
            # anything that's left must be a version tag.
            echo "::set-output name=tag::${ref#refs/tags/}"
          fi
        fi
    - name: Build and tag image
      run: |
        docker build -t "docker.pkg.github.com/$GITHUB_REPOSITORY/marathon-acme-trio:${{ steps.tag.outputs.tag }}" .
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Publish to GPR
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/marathon-acme-trio:${{ steps.tag.outputs.tag }}"
  pullFromGPR:
    needs: RegistryPush
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Pull Docker image
      run: |
        docker pull "docker.pkg.github.com/$GITHUB_REPOSITORY/marathon-acme-trio:${{ needs.RegistryPush.outputs.image-tag }}"
        echo docker.pkg.github.com/$GITHUB_REPOSITORY/marathon-acme-trio:${{ needs.RegistryPush.outputs.image-tag }}
        echo tafymunya/mara:${{ needs.RegistryPush.outputs.image-tag }}
        docker login docker.pkg.github.com --username=tafymunya --password=Tafy2392@
        docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/marathon-acme-trio:${{ needs.RegistryPush.outputs.image-tag }} \
        tafymunya/mara:${{ needs.RegistryPush.outputs.image-tag }}
        docker push tafymunya/mara:${{ needs.RegistryPush.outputs.image-tag }}




