name: continuous integration
on:
  - pull_request

jobs:
  testOnPullRequest:
    name: build_and_release_on_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF}
