name: continuous integration
on:
  - pull_request

jobs:
  testOnPullRequest:
    name: build_and_release_on_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: |
          echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
          BASE_BRANCH: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
